version: "3"

services:
    beale:
        container_name: beale
        image: nginx
        volumes:
            - ./dev.conf:/etc/nginx/nginx.conf
            - ./html/index.html:/etc/nginx/html/index.html
        ports:
            - "8080:8080"
        command: "/bin/sh -c 'nginx -g \"daemon off;\"'"
